# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "duplicati_http_header_content_permission_policy", "new": "duplicati_http_header_permissions_policy" }

- name: Fail if required Duplicati settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - duplicati_uid
    - duplicati_gid
    - duplicati_hostname
    - duplicati_path_prefix
    - duplicati_container_network
    - duplicati_source_path
    - duplicati_environment_variable_settings_encryption_key
    - duplicati_environment_variable_duplicati__webservice_password

- name: Run if Traefik is enabled
  when: duplicati_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Duplicati are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - duplicati_container_labels_traefik_hostname
        - duplicati_container_labels_traefik_path_prefix

    - name: Fail if duplicati_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          duplicati_container_labels_traefik_path_prefix (`{{ duplicati_container_labels_traefik_path_prefix }}`) must be `/`.
          Duplicati does not support hosting under a subpath yet.
      when: "duplicati_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `duplicati_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if duplicati_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          duplicati_container_labels_traefik_path_prefix (`{{ duplicati_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/duplicati`).
      when: "duplicati_container_labels_traefik_path_prefix != '/' and duplicati_container_labels_traefik_path_prefix[-1] == '/'"
